name: Deploy Angular Application to S3

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js with version 18
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.2.0

      # Install project dependencies
      - name: Install dependencies
        run: npm ci

      # Build Angular app (adjust project name if necessary)
      - name: Build Angular App
        run: npm run build -- --configuration production

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your bucket's region

      # Sync build output to S3
      - name: Deploy to S3
        run: aws s3 sync ./dist/ s3://www.jorgechavezuiuc.com --delete
        
