name: Deploy Angular Application to S3

on:
  push:
    branches:
      - master
env:
  AWS_REGION: us-east-1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.2.0

      # Install project dependencies
      - name: Install dependencies
        run: npm ci

      # Get the timestamp of the last Git commit from the project and
      # save it as the environment variable, LAST_UPDATED. Store it in Github
      # action's environment.
      - name: Set LAST_UPDATED env variable from Git commit timestamp
        run: echo "LAST_UPDATED=$(git log -1 --format=%cI)" >> $GITHUB_ENV

      # Update the production environment file
      # -i: Modify the file inplace.
      # Substitution command has pattern: s/<pattern>/<replacement>/
      # <pattern>: masterLastUpdated: '.*', ;; Finds a patter for this variable with single quotations
      # <replacement>: masterLastUpdated: '${MASTER_LAST_UPDATED}', ;; replaces the contents with the env variable set
      - name: Inject LAST_UPDATED into environment.prod.ts
        run: |
          sed -i "s/masterLastUpdated: '.*'/masterLastUpdated: '${MASTER_LAST_UPDATED}',/" src/environments/environment.prod.ts

      # Build Angular app
      - name: Build Angular App
        run: npm run build -- --configuration production

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}  # my bucket's region

      # Sync build output to S3
      # Delete old files
      # Make new files public readable by acl as this is for a hosted website
      - name: Deploy to S3
        run: aws s3 sync ./dist/updated-personal-website/browser s3://www.jorgechavezuiuc.com --delete --acl public-read

      # Create CloudFront invalidation to serve the new files in the bucket
      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

